name: Web Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on:
      ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Config of Git
        run: |
          git config user.name "${{ secrets.NAME }}"
          git config user.email "${{ secrets.EMAIL }}"

      - name: Fetch and Pull
        run: |
          git fetch origin main
          git pull origin main
      
      - name: Installing Dependencies
        run: |
          npm install
          npm install gh-pages

      - name: Deploying to GH Pages
        run: |
          npm run build
          npx gh-pages -b deploy -d dist -m '${{ github.event.head_commit.message }}' --cname ryannkim327.is-a.dev

        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
